FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src

COPY /src/ ./

RUN dotnet publish Minitwit.API -c Release -o /Release

EXPOSE 5050
ENV ASPNETCORE_URLS=http://*:5050

WORKDIR /Release
ENTRYPOINT ["dotnet", "Minitwit.API.dll"]
