FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src

COPY /src/ ./

RUN mkdir -p /data
RUN dotnet publish Minitwit.API -c Release -o /Release

EXPOSE 8080
ENV ASPNETCORE_URLS=http://*:5050

WORKDIR /Release
ENTRYPOINT ["dotnet", "Minitwit.API.dll"]
