version: "3"

networks:
  minitwit-network:
    external: false
    name: minitwit-network

volumes:
  grafana-storage:
  prom_data:

services:
  minitwit-web:
    build:
      context: .
      dockerfile: Dockerfile-web
    image: group-n/minitwit-web
    container_name: minitwit-web
    volumes:
      - /tmp/connstring.txt:/data/connstring.txt
    ports:
      - "8080:8080"
    user: "root"
    networks:
      - minitwit-network
    depends_on:
      - prometheus
      - grafana

  minitwit-api:
    build:
      context: .
      dockerfile: Dockerfile-api
    image: group-n/minitwit-api
    container_name: minitwit-api
    volumes:
      - /tmp/connstring.txt:/data/connstring.txt
    ports:
      - "5050:5050"
    user: "root"
    networks:
      - minitwit-network
    depends_on:
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./remote_files/prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - minitwit-network

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - minitwit-network
