FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src

COPY /src/ ./
COPY /src/Minitwit.API/schema.sql /tmp/schema.sql

RUN dotnet publish Minitwit.Web -c Release -o /Release

EXPOSE 8080
ENV ASPNETCORE_URLS=http://*:8080

WORKDIR /Release
ENTRYPOINT ["dotnet", "Minitwit.Web.dll"]
