FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src

COPY /src/ ./

RUN mkdir -p /data 
RUN dotnet publish Minitwit.Web -c Release -o /Release

EXPOSE 8080
ENV ASPNETCORE_URLS=http://*:8080
ENV ASPNETCORE_ENVIRONMENT=Development

WORKDIR /Release
ENTRYPOINT ["dotnet", "Minitwit.Web.dll"]
