version: "3.8"

networks:
  minitwit-network:
    external: false
    name: minitwit-network

volumes:
  vagrant_prom_data:
    external: true
  vagrant_grafana_storage:
    external: true

services:
  minitwit-web-image:
    image: dsmillard/minitwit-web
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
      placement:
        max_replicas_per_node: 2
        constraints:
          - node.role!=manager
    volumes:
      - /data/connstring.txt:/data/connstring.txt
    ports:
      - "8080:8080"
    networks:
      - minitwit-network
    depends_on:
      - prometheus
      - grafana

  minitwit-api-image:
    image: dsmillard/minitwit-api
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
      placement:
        max_replicas_per_node: 2
        constraints:
          - node.role!=manager
    volumes:
      - /data/connstring.txt:/data/connstring.txt
    ports:
      - "5050:5050"
    networks:
      - minitwit-network
    depends_on:
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    deploy:
      placement:
        constraints:
          - node.role==manager
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - vagrant_prom_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - minitwit-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    deploy:
      placement:
        constraints:
          - node.role==manager
    volumes:
      - vagrant_grafana_storage:/var/lib/grafana:rw
    networks:
      - minitwit-network
