version: '3.3'

networks:
  main:

services:

  minitwit-web-image:
    image: ${DOCKER_USERNAME}/minitwit-web
    container_name: minitwit-web
    networks:
      - main
    ports:
        - '8080:8080'

  minitwit-api-image:
    image: ${DOCKER_USERNAME}/minitwit-api
    container_name: minitwit-api
    networks:
      - main
    ports:
      - '5050:5050'
    environment:
        - MYSQL_ROOT_PASSWORD=root
