version: "3"

networks:
  minitwit-network:
    external: false
    name: minitwit-network

volumes:
  prom_data:
  grafana_storage:

services:
  minitwit-web-image:
    image: dsmillard/minitwit-web
    container_name: minitwit-web
    volumes:
      - /data/connstring.txt:/data/connstring.txt
    ports:
      - "8080:8080"
    networks:
      - minitwit-network
    depends_on:
      - prometheus
      - grafana

  minitwit-api-image:
    image: dsmillard/minitwit-api
    container_name: minitwit-api
    volumes:
      - /data/connstring.txt:/data/connstring.txt
    ports:
      - "5050:5050"
    networks:
      - minitwit-network
    depends_on:
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - minitwit-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana:rw
    networks:
      - minitwit-network