global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["prometheus:PORT"] # define port to match docker-compose.yml

  - job_name: "minitwit"

    scrape_interval: 5s

    static_configs:
      - targets: ["minitwit-web:PORT", "minitwit-api:PORT"] # define port to match docker-compose.yml
        labels:
          group: "production"
