global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["prometheus:9090"] # DO NOT REMOVE PORT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  - job_name: "minitwit"

    scrape_interval: 5s

    static_configs:
      - targets: ["minitwit-web:8080", "minitwit-api:5050"] # DO NOT REMOVE PORT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        labels:
          group: "production"
