name: Compile Latex and Release PDF  

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - "report/**"
      - "!report/build/**"
  workflow_dispatch:
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with: 
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push 
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: report/
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: BSc_group_n
          path: report/main.pdf

      # - name: Commit & Push changes
      #   run: |
      #     git config --global user.email "raln@itu.dk"
      #     git config --global user.name "GitHub Action"
      #     git add report/build/main.pdf
      #     git commit -m "Automated PDF build"
      #     git push https://rlnprogrammering:${{ secrets.ACTIONS_PAT }}@github.com/itu-devops-groupn/itu-minitwit.git HEAD:main