---
# The workflow is adapted from the following guide:
# https://github.com/itu-devops/itu-minitwit-ci/blob/master/README.md
name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Autorelease"]
    types:
      - completed
  # allow manual triggers for now too
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get latest Git tag
        id: latest_tag
        run: echo "::set-output name=tag::$(git describe --tags $(git rev-list --tags --max-count=1))"

      - name: Build and push Minitwit-web image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile-web
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minitwit-web:${{ steps.latest_tag.outputs.tag }}

      - name: Build and push Minitwit-api image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile-api
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minitwit-api:${{ steps.latest_tag.outputs.tag }}

      # - name: Configure SSH
      #   run: |
      #     mkdir -p ~/.ssh/
      #     echo "$SSH_KEY" > ~/.ssh/do_ssh_key
      #     chmod 600 ~/.ssh/do_ssh_key
      #   env:
      #     SSH_KEY: |
      #       ${{ secrets.SSH_KEY }}

      # - name: Deploy to server
      #   # Configure the ~./bash_profile and deploy.sh file on the Vagrantfile
      #   run: >
      #     ssh "$SSH_USER@$SSH_HOST" -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no "/vagrant/deploy.sh '${{ steps.latest_tag.outputs.tag }}'"
      #   env:
      #     SSH_USER: ${{ secrets.SSH_USER }}
      #     SSH_HOST: ${{ secrets.SSH_HOST }}
