---
# The workflow is adapted from the following guide:
# https://github.com/itu-devops/itu-minitwit-ci/blob/master/README.md
name: Continuous Deployment

on:
  push:
    # Run workflow every time something is pushed to the master branch
    branches:
    - main
  # allow manual triggers for now too
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Minitwit-web image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile-web
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minitwit-web

      - name: Build and push Minitwit-api image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile-api
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minitwit-api

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/do_ssh_key
          chmod 600 ~/.ssh/do_ssh_key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        # Configure the ~./bash_profile and deploy.sh file on the Vagrantfile
        run: >
          ssh $SSH_USER@$SSH_HOST
          -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no
          '/vagrant/deploy.sh'
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
