name: UI Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker Compose
      run: docker-compose up --build -d

    - name: Wait for services to start
      run: sleep 80s

    - name: Run Playwright Tests
      run: |
        docker run \
          -v "$(pwd)/test/PlaywrightTests:/src/test/PlaywrightTests" \
          -w /src/test/PlaywrightTests \
          -e DOCKER_NETWORK=localhost \
          mcr.microsoft.com/playwright/dotnet:v1.43.0-jammy \
          dotnet test ./PlaywrightTests.csproj
