name: Playwright Tests

on:
  push:
    branches:
      - test/playwright-test

jobs:
  jobs:
  build-and-up:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/compose-cli-action@v0.1.0
        with:
          version: '2'

      - name: Build and Start Docker services
        run: |
          docker compose build
          docker compose up -d

      - name: Run Playwright tests
          run: |
            docker run \
              --network minitwit-network \
              -v "$(pwd)/test/PlaywrightTests:/src/test/PlaywrightTests" \
              -w /src/test/PlaywrightTests \
              -e DOCKER_NETWORK=minitwit-network \
              mcr.microsoft.com/playwright/dotnet:v1.43.0-jammy \
              dotnet test ./PlaywrightTests.csproj