name: Playwright Tests

on: commit

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      minitwit-web:
        image: ${{ secrets.DOCKER_USERNAME }}/minitwit-web:latest
        ports:
          - "8080:8080"
        networks:
          - minitwit-network

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Playwright tests
        uses: docker://mcr.microsoft.com/playwright/dotnet:v1.43.0-jammy
        with:
          args: >
            dotnet test /src/test/PlaywrightTests/PlaywrightTests.csproj
        env:
          MINITWIT_URL: http://minitwit-web:8080  # Set URL for minitwit-web service

networks:
  minitwit-network:
    driver: bridge
