name: UI Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure volume
      run: |
        mkdir -p /tmp
        echo "$CONN_STRING" > /tmp/connstring.txt
        chmod +rw /tmp/connstring.txt
      env: 
        CONN_STRING: |
         ${{ secrets.connString }}

    - name: Setup Docker Compose
      run: docker-compose build

    - name: Setup Docker Compose
      run: docker-compose up

    - name: Run Playwright Tests
      run: |
        docker run \
          --network minitwit-network \
          -v "$(pwd)/test/PlaywrightTests:/src/test/PlaywrightTests" \
          -w /src/test/PlaywrightTests \
          -e DOCKER_NETWORK=minitwit-network \
          mcr.microsoft.com/playwright/dotnet:v1.43.0-jammy \
          dotnet test ./PlaywrightTests.csproj
